name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'
    - name: Create and activate conda env
      run: |
        #
        conda init && echo "conda init"
        myenv=`basename "$PWD"`
        conda create --name $myenv -y
        echo "Activating $myenv"
        conda activate $myenv && echo "activated"
        # conda env update --file environment.yml --name $myenv
    - name: Install python-kubernetes
      run: |
        echo "Installing python-kubernetes"
        conda config --add channels conda-forge 
        conda config --set channel_priority strict
        conda install kubernetes kubernetes-client kubernetes-node kubernetes-server -y
        conda install python-kubernetes -y
    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
